### ISSUE TITLE
Create sample route ini file

### ISSUE THREAD

**Issue by dimkasta** [dimkasta/F3-UAM#15]
Already exists and is updated as the demo site is populated and the class is made more plug and play with existing code.

**Comment by pannet1** [comment]
hi dimkasta,

I am unable to make this work. Could you please include sample file in the github repository as well. For example need:-

1) route entries.
2) AUTOLOAD= entry
3) view files
4) User Class code additions to make this views work.

**Comment by dimkasta** [comment]
Irrelevant for newer version

It will include a completely functional ini file
